vich_uploader:
    db_driver: orm
    mappings:
        material_image:
            uri_prefix: assets/images/uploads/materials
            upload_destination: '%kernel.project_dir%/public/assets/images/uploads/materials'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
