vich_uploader:
    db_driver: orm
    mappings:
        material_image:
            uri_prefix: /uploads/materials
            upload_destination: '%kernel.project_dir%/public/uploads/materials'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: true
            directory_namer: ~
