vich_uploader:
    db_driver: orm
    mappings:
        material_image:
            uri_prefix: /uploads/materials
            upload_destination: '%kernel.project_dir%/public/uploads/materials'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
