controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

material_details:
    path: '/material/{slug}'
    controller: 'App\Controller\MaterialController::materialDetails'