controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

material_detail:
    path: /material/{id}
    controller: App\Controller\MaterialController::detail
    requirements:
        id: \d+